const spreads=[
{l:`<div class="page-head"><span class="kicker">MANUEL MÉDIC SHAMAD</span><span class="page-no">PAGE 01</span></div><h2>Sommaire</h2><div class="toc">
<button data-go="1"><span class="num">01</span><span>Rôle du Médic</span><span>p.03</span></button>
<button data-go="2"><span class="num">02</span><span>Médic Niveau 1</span><span>p.04</span></button>
<button data-go="2"><span class="num">03</span><span>Médic Niveau 2</span><span>p.05</span></button>
<button data-go="3"><span class="num">04</span><span>Pouls HR</span><span>p.06</span></button>
<button data-go="3"><span class="num">05</span><span>Pression sanguine BP</span><span>p.07</span></button>
<button data-go="4"><span class="num">06</span><span>Hémorragies</span><span>p.08</span></button>
<button data-go="4"><span class="num">07</span><span>Médicaments</span><span>p.09</span></button>
<button data-go="5"><span class="num">08</span><span>Protocoles SHAMAD</span><span>p.10</span></button>
<button data-go="5"><span class="num">09</span><span>Questions théoriques</span><span>p.11</span></button>
<button data-go="6"><span class="num">10</span><span>Examen final / QCM</span><span>p.12</span></button></div>`,r:`<div class="page-head"><span class="kicker">SHAMAD MEDICAL ACADEMY</span><span class="page-no">PAGE 02</span></div><h2>Doctrine</h2><div class="cards"><div class="card"><h3>Devise</h3><p>Un soin. Une vie. Une mission.</p></div><div class="alert"><strong>Delta Médic</strong><p>Si le médic est Delta, la mission est compromise.</p></div><div class="card"><h3>Règle d'or</h3><p>On ne perfuse jamais un patient qui saigne encore.</p></div><div class="card"><h3>Constantes</h3><p>Les deux constantes centrales sont le pouls HR et la pression sanguine BP.</p></div></div>`},
{l:`<div class="page-head"><span class="kicker">SECTION 01</span><span class="page-no">PAGE 03</span></div><h2>Rôle du Médic</h2><div class="cards"><div class="card"><h3>Mission</h3><p>Sauver, stabiliser, transmettre et préparer l’évacuation.</p></div><div class="card"><h3>Priorités</h3><ol><li>Sécuriser</li><li>Stopper l'hémorragie</li><li>Vérifier HR/BP</li><li>Traiter</li><li>Évacuer</li></ol></div><div class="alert"><strong>Règle Delta</strong><p>Le médic est une ressource critique.</p></div><div class="card"><h3>Conduite</h3><p>Rester calme, informer, respecter les protocoles SHAMAD.</p></div></div>`,r:`<div class="page-head"><span class="kicker">SECTION 02</span><span class="page-no">PAGE 04</span></div><h2>Médic N1</h2><div class="cards"><div class="card"><h3>Autorisé</h3><ul><li>Pouls HR</li><li>Pression BP</li><li>Garrot</li><li>Bandage</li><li>PLS</li><li>Transmission au N2</li></ul></div><div class="card red"><h3>Limites</h3><ul><li>Pas de médicaments avancés</li><li>Pas de saline seul</li><li>Pas de gestion critique seul</li></ul></div></div>`},
{l:`<div class="page-head"><span class="kicker">SECTION 03</span><span class="page-no">PAGE 05</span></div><h2>Médic N2</h2><div class="cards"><div class="card"><h3>Capacités</h3><ul><li>Toutes les actions N1</li><li>Médicaments</li><li>Saline selon protocole</li><li>Cas critiques</li><li>EVASAN</li></ul></div><div class="alert"><strong>Responsabilité</strong><p>Le N2 dirige la prise en charge médicale sur le terrain.</p></div></div>`,r:`<div class="page-head"><span class="kicker">SECTION 04</span><span class="page-no">PAGE 06</span></div><h2>Pouls HR</h2><div class="ecg"></div><div class="rows"><div class="row"><strong>Stable</strong><span>60-100 BPM — surveillance.</span></div><div class="row"><strong>Bas</strong><span>40-60 BPM — surveiller et rechercher la cause.</span></div><div class="row"><strong>Critique</strong><span>&lt; 40 BPM — épinéphrine possible.</span></div><div class="row"><strong>Tachycardie</strong><span>&gt; 140 BPM — métoprolol possible si BP correcte.</span></div></div>`},
{l:`<div class="page-head"><span class="kicker">SECTION 05</span><span class="page-no">PAGE 07</span></div><h2>Pression BP</h2><div class="bpbar"></div><div class="rows"><div class="row"><strong>Stable</strong><span>120/80 — surveillance standard.</span></div><div class="row"><strong>Faible</strong><span>100/60 — surveiller.</span></div><div class="row"><strong>Critique</strong><span>&lt; 90/60 — saline si hémorragie contrôlée.</span></div><div class="row"><strong>Urgence</strong><span>&lt; 70/50 — phényléphrine possible.</span></div><div class="row"><strong>Extrême</strong><span>&lt; 60/40 — urgence absolue.</span></div></div><div class="alert"><strong>Saline</strong><p>Jamais si le patient saigne encore.</p></div>`,r:`<div class="page-head"><span class="kicker">SECTION 06</span><span class="page-no">PAGE 08</span></div><h2>Hémorragies</h2><div class="rows"><div class="row"><strong>Classe I</strong><span>Légère — bandage, pas de saline.</span></div><div class="row"><strong>Classe II</strong><span>Modérée — bandage/garrot, surveillance.</span></div><div class="row"><strong>Classe III</strong><span>Grave — garrot/bandages + saline si contrôlée.</span></div><div class="row"><strong>Classe IV</strong><span>Critique — mort imminente, EVASAN urgente.</span></div></div><div class="alert"><strong>Priorité</strong><p>Contrôler l’hémorragie avant tout traitement.</p></div>`},
{l:`<div class="page-head"><span class="kicker">SECTION 07</span><span class="page-no">PAGE 09</span></div><h2>Médicaments</h2><div class="grid"><div class="med"><h3>Bandage</h3><p>Saignements simples.</p></div><div class="med"><h3>Garrot</h3><p>Hémorragie massive sur membre.</p></div><div class="med"><h3>Saline</h3><p>BP &lt; 90/60 si hémorragie contrôlée.</p></div><div class="med"><h3>Morphine</h3><p>Douleur, patient stable uniquement.</p></div><div class="med"><h3>Épinéphrine</h3><p>HR &lt; 40 BPM ou CPR.</p></div><div class="med"><h3>Métoprolol</h3><p>HR &gt; 140 BPM, éviter si BP faible.</p></div><div class="med"><h3>Phényléphrine</h3><p>BP &lt; 70/50.</p></div><div class="med"><h3>Naloxone / Carbonate</h3><p>Selon diagnostic ou réveil stabilisé.</p></div></div>`,r:`<div class="page-head"><span class="kicker">SECTION 08</span><span class="page-no">PAGE 10</span></div><h2>Protocoles</h2><ol><li>Sécuriser la zone.</li><li>Évaluer l’état du patient.</li><li>Contrôler les hémorragies.</li><li>Vérifier HR/BP.</li><li>Administrer le traitement adapté.</li><li>Stabiliser.</li><li>Préparer l’évacuation.</li></ol><div class="cards"><div class="card"><h3>PLS</h3><p>Patient inconscient mais stabilisé.</p></div><div class="card"><h3>Massage cardiaque</h3><p>HR très basse ou arrêt probable.</p></div></div>`},
{l:`<div class="page-head"><span class="kicker">SECTION 09</span><span class="page-no">PAGE 11</span></div><h2>Questions</h2><div class="rows"><div class="row"><strong>Q1</strong><span>À partir de quelle HR utiliser l’épinéphrine ? HR &lt; 40 BPM.</span></div><div class="row"><strong>Q2</strong><span>Quand ne pas poser une saline ? Hémorragie active.</span></div><div class="row"><strong>Q3</strong><span>Rôle du garrot ? Contrôler une hémorragie sévère d’un membre.</span></div><div class="row"><strong>Q4</strong><span>Médic Delta ? Mission compromise.</span></div><div class="row"><strong>Q5</strong><span>Priorité N1 ? Sauver la vie du patient.</span></div></div>`,r:`<div class="page-head"><span class="kicker">SECTION 10</span><span class="page-no">PAGE 12</span></div><h2>Examen Final</h2><div class="quiz"><div><strong id="progress">Question 1 / 10</strong> — <strong id="score">Score : 0</strong></div><h3 id="question"></h3><div id="answers" class="quiz"></div><p id="feedback"></p><button class="main-btn" id="nextQuestion">Question suivante</button><button class="ghost-btn" id="restartQuiz">Recommencer</button></div>`}
];

const questions=[
["Première action face à une hémorragie massive ?",["Morphine","Garrot/Bandage","Saline","PLS"],1],
["HR 35 BPM : traitement possible ?",["Métoprolol","Épinéphrine","Morphine","Aucun"],1],
["BP 65/45 : médicament possible ?",["Phényléphrine","Métoprolol","Morphine","Naloxone"],0],
["Peut-on poser une saline si le patient saigne encore ?",["Oui","Non","Toujours","Seulement classe I"],1],
["HR > 140 correspond à...",["Tachycardie","Arrêt","Stable","BP faible"],0],
["Métoprolol s’utilise si...",["HR > 140","HR < 40","BP < 60/40","Classe I"],0],
["Épinéphrine s’utilise si...",["HR < 40","HR > 140","BP normale","Stable"],0],
["Classe IV signifie...",["Légère","Modérée","Critique","Stable"],2],
["Médic Delta signifie...",["Mission normale","Mission compromise","Plus de soin","Rien"],1],
["Priorité du médic ?",["Rester vivant et sauver l’unité","Faire des kills","Partir seul","Ignorer HR/BP"],0]
];

const cover=document.getElementById('cover'),reader=document.getElementById('reader'),openBtn=document.getElementById('openBtn'),left=document.getElementById('leftPage'),right=document.getElementById('rightPage'),prev=document.getElementById('prevBtn'),next=document.getElementById('nextBtn'),count=document.getElementById('pageCount'),flip=document.getElementById('flip');
let idx=0,mobile=0,turning=false,qi=0,score=0,locked=false;
function isMobile(){return innerWidth<=820}
openBtn.onclick=()=>{cover.classList.add('hidden');reader.classList.remove('hidden');render()}
function render(){if(isMobile()){left.classList.remove('mobile-active');right.classList.add('mobile-active');let p=Math.floor(mobile/2),side=mobile%2?'r':'l';right.innerHTML=spreads[p][side];count.textContent=`${mobile+1} / 12`;prev.disabled=mobile===0;next.disabled=mobile===11;if(mobile===11)initQuiz()}else{left.classList.remove('mobile-active');right.classList.remove('mobile-active');left.innerHTML=spreads[idx].l;right.innerHTML=spreads[idx].r;count.textContent=`${idx*2+1}-${idx*2+2} / 12`;prev.disabled=idx===0;next.disabled=idx===spreads.length-1;if(idx===5)initQuiz()}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{idx=Number(b.dataset.go);mobile=idx*2;render()})}
function turn(d){if(turning)return;if(isMobile()){let t=mobile+d;if(t<0||t>11)return;mobile=t;render();return}let t=idx+d;if(t<0||t>=spreads.length)return;turning=true;flip.className='flip '+(d>0?'next':'prev');setTimeout(()=>{idx=t;render()},310);setTimeout(()=>{flip.className='flip';turning=false},680)}
prev.onclick=()=>turn(-1);next.onclick=()=>turn(1);onresize=render;
function initQuiz(){qi=0;score=0;locked=false;drawQ();let nq=document.getElementById('nextQuestion'),rs=document.getElementById('restartQuiz');if(nq)nq.onclick=()=>{if(qi<questions.length-1){qi++;drawQ()}else{document.getElementById('question').textContent='Examen terminé';document.getElementById('answers').innerHTML='';document.getElementById('feedback').textContent=`Résultat : ${score}/10 — ${score>=8?'Certifié':'À revoir'}`}};if(rs)rs.onclick=()=>{qi=0;score=0;drawQ()}}
function drawQ(){let q=document.getElementById('question'),a=document.getElementById('answers'),p=document.getElementById('progress'),s=document.getElementById('score'),f=document.getElementById('feedback');if(!q)return;locked=false;p.textContent=`Question ${qi+1} / 10`;s.textContent=`Score : ${score}`;q.textContent=questions[qi][0];a.innerHTML='';f.textContent='';questions[qi][1].forEach((txt,i)=>{let b=document.createElement('button');b.className='answer';b.textContent=String.fromCharCode(65+i)+' — '+txt;b.onclick=()=>{if(locked)return;locked=true;[...a.children].forEach((x,j)=>{if(j===questions[qi][2])x.classList.add('correct');if(j===i&&j!==questions[qi][2])x.classList.add('wrong')});if(i===questions[qi][2])score++;s.textContent=`Score : ${score}`;f.textContent=i===questions[qi][2]?'✅ Bonne réponse':'❌ Mauvaise réponse'};a.appendChild(b)})}
